In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Numpy Exercises

### Exercise 1

In [41]:
x = np.r_[1,2,3]
y = np.r_[4,5,6]

In [42]:
np.dot(x,y)

32

In [54]:
np.sum(x*y)

32

In [21]:
a = np.r_[1,2,3,4,5,6,7,8]
b = np.r_[9,10,11,12,13,14,15,16]

np.dot(a,b)

492

### Exercise 2

In [52]:
c = np.r_[1,5,9,7,6]
d = np.r_[3,2,5,10,12]

In [53]:
(1/len(c))*np.sum(np.abs(d-c))

3.6

### Exercise 3

In [80]:
def lag(x, n):
    x = np.delete(x, np.s_[len(x)-n:])
    x = np.append(x, np.repeat(np.NaN, n))
    return x

In [83]:
lag([1,2,3,4,5], 2)

array([ 1.,  2.,  3., nan, nan])

In [118]:
def lead(x, n):
    x = np.array(x, dtype=np.float) #convert values in array so that NaN can be inserted
    x = np.delete(x, np.s_[:n])
    x = np.insert(x, 0, np.repeat(np.NaN, n))
    return x

In [121]:
lead([1,2,3,4,5], 2)

array([nan, nan,  3.,  4.,  5.])

### Exercise 4

In [246]:
A = np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12]
])

In [247]:
b = np.array([3,3,3])

In [272]:
def distance(X, y):
    for a in range(X.shape[1]):
        print(np.abs(X[:,a]-y))

In [273]:
distance(A,b)

[2 2 6]
[1 3 7]
[0 4 8]
[1 5 9]


# Pandas Exercises

### Exercise 1

In [59]:
data_weather = pd.read_csv("nycflights13_weather.csv", sep=',',skiprows=42, header=0)

In [60]:
data_weather.head()

origin  year  month  day  hour   temp   dewp  humid  wind_dir  wind_speed  \
0    EWR  2013      1    1     0  37.04  21.92  53.97     230.0    10.35702   
1    EWR  2013      1    1     1  37.04  21.92  53.97     230.0    13.80936   
2    EWR  2013      1    1     2  37.94  21.92  52.09     230.0    12.65858   
3    EWR  2013      1    1     3  37.94  23.00  54.51     230.0    13.80936   
4    EWR  2013      1    1     4  37.94  24.08  57.04     240.0    14.96014   

   wind_gust  precip  pressure  visib            time_hour  
0  11.918651     0.0    1013.9   10.0  2013-01-01 01:00:00  
1  15.891535     0.0    1013.0   10.0  2013-01-01 02:00:00  
2  14.567241     0.0    1012.6   10.0  2013-01-01 03:00:00  
3  15.891535     0.0    1012.7   10.0  2013-01-01 04:00:00  
4  17.215830     0.0    1012.8   10.0  2013-01-01 05:00:00

### Temperature Conversion

In [61]:
#F = 1.8C + 32 => C = (F - 32)/1.8

In [62]:
data_weather['temp'] = np.round((data_weather['temp'] - 32)/1.8, 4)

In [63]:
data_weather.head()

origin  year  month  day  hour  temp   dewp  humid  wind_dir  wind_speed  \
0    EWR  2013      1    1     0   2.8  21.92  53.97     230.0    10.35702   
1    EWR  2013      1    1     1   2.8  21.92  53.97     230.0    13.80936   
2    EWR  2013      1    1     2   3.3  21.92  52.09     230.0    12.65858   
3    EWR  2013      1    1     3   3.3  23.00  54.51     230.0    13.80936   
4    EWR  2013      1    1     4   3.3  24.08  57.04     240.0    14.96014   

   wind_gust  precip  pressure  visib            time_hour  
0  11.918651     0.0    1013.9   10.0  2013-01-01 01:00:00  
1  15.891535     0.0    1013.0   10.0  2013-01-01 02:00:00  
2  14.567241     0.0    1012.6   10.0  2013-01-01 03:00:00  
3  15.891535     0.0    1012.7   10.0  2013-01-01 04:00:00  
4  17.215830     0.0    1012.8   10.0  2013-01-01 05:00:00

### Daily Mean Temperatures for the JFK Airport

In [64]:
data_weather["date"] = data_weather["year"].map(str) + data_weather["month"].map(str) + data_weather["day"].map(str)

In [65]:
data_weather["date"] = data_weather["date"].map(int) #convert to int for sorting purposes

In [72]:
data_weather.head()

origin  year  month  day  hour  temp   dewp  humid  wind_dir  wind_speed  \
0    EWR  2013      1    1     0   2.8  21.92  53.97     230.0    10.35702   
1    EWR  2013      1    1     1   2.8  21.92  53.97     230.0    13.80936   
2    EWR  2013      1    1     2   3.3  21.92  52.09     230.0    12.65858   
3    EWR  2013      1    1     3   3.3  23.00  54.51     230.0    13.80936   
4    EWR  2013      1    1     4   3.3  24.08  57.04     240.0    14.96014   

   wind_gust  precip  pressure  visib            time_hour    date  
0  11.918651     0.0    1013.9   10.0  2013-01-01 01:00:00  201311  
1  15.891535     0.0    1013.0   10.0  2013-01-01 02:00:00  201311  
2  14.567241     0.0    1012.6   10.0  2013-01-01 03:00:00  201311  
3  15.891535     0.0    1012.7   10.0  2013-01-01 04:00:00  201311  
4  17.215830     0.0    1012.8   10.0  2013-01-01 05:00:00  201311

In [69]:
jfk_avg_temp = data_weather[["temp", "date"]][data_weather["origin"] == "JFK"].groupby("date").mean()

In [70]:
jfk_avg_temp.head()

temp
date            
201311  3.817391
201312 -1.920833
201313 -1.237500
201314  1.129167
201315  2.720833

### Greater mean temperature than on the preceding day

In [47]:
avg_temp = data_weather[["temp", "date"]].groupby("date").mean().reset_index()

In [49]:
avg_temp.head()

date      temp
0  201311  3.813043
1  201312 -1.833333
2  201313 -1.308333
3  201314  1.254167
4  201315  2.845833

In [57]:
for row in range(1,len(avg_temp)):
    if avg_temp["temp"][row] > avg_temp["temp"][row-1]:
        print(avg_temp["date"][row])

201313
201314
201315
201316
201317
201319
201323
201324
201325
201326
201328
201331
201334
201335
201336
201339
201341
201343
201344
201345
201347
201348
201349
201352
201356
201357
201358
201361
201368
201369
201371
201372
201373
201374
201375
201376
201377
201382
201386
201387
201388
201389
201391
201397
201398
2013101
2013102
2013104
2013107
2013111
2013112
2013116
2013117
2013119
2013120
2013124
2013125
2013126
2013129
2013130
2013131
2013211
2013212
2013214
2013215
2013219
2013222
2013223
2013224
2013226
2013227
2013228
2013311
2013312
2013315
2013316
2013319
2013320
2013323
2013324
2013326
2013327
2013329
2013330
2013410
2013413
2013414
2013416
2013417
2013419
2013422
2013424
2013425
2013426
2013427
2013428
2013430
2013510
2013515
2013516
2013520
2013521
2013523
2013526
2013527
2013529
2013530
2013531
2013611
2013612
2013615
2013616
2013617
2013620
2013621
2013622
2013623
2013624
2013625
2013630
2013710
2013711
2013714
2013715
2013716
2013717
2013718
2013719
2013723
2013724
20137

In [56]:
avg_temp["temp"][1] > avg_temp["temp"][0]

False

###  5 Hottest days

In [24]:
avg_temp = data_weather[["temp", "date"]].groupby("date").mean()

In [34]:
hottest_days = avg_temp["temp"].nlargest(5)

In [35]:
hottest_days

date
2013719    32.233333
2013718    31.395833
2013720    30.912500
2013717    30.719444
2013716    30.548611
Name: temp, dtype: float64

### Exercise 2

In [3]:
data_flights = pd.read_csv("nycflights13_flights.csv", sep=',',skiprows=54, header=0)

In [4]:
data_flights.head()

year  month  day  dep_time  sched_dep_time  dep_delay  arr_time  \
0  2013      1    1     517.0             515        2.0     830.0   
1  2013      1    1     533.0             529        4.0     850.0   
2  2013      1    1     542.0             540        2.0     923.0   
3  2013      1    1     544.0             545       -1.0    1004.0   
4  2013      1    1     554.0             600       -6.0     812.0   

   sched_arr_time  arr_delay carrier  flight tailnum origin dest  air_time  \
0             819       11.0      UA    1545  N14228    EWR  IAH     227.0   
1             830       20.0      UA    1714  N24211    LGA  IAH     227.0   
2             850       33.0      AA    1141  N619AA    JFK  MIA     160.0   
3            1022      -18.0      B6     725  N804JB    JFK  BQN     183.0   
4             837      -25.0      DL     461  N668DN    LGA  ATL     116.0   

   distance  hour  minute            time_hour  
0      1400     5      15  2013-01-01 05:00:00  
1      1416     5      29  2013-01-01 05:00:00  
2      1089     5      40  2013-01-01 05:00:00  
3      1576     5      45  2013-01-01 05:00:00  
4       762     6       0  2013-01-01 06:00:00

In [12]:
data_flights.iloc[:,0:3].head()

year  month  day
0  2013      1    1
1  2013      1    1
2  2013      1    1
3  2013      1    1
4  2013      1    1

In [16]:
data_flights[['year', 'month', 'day']].head()

year  month  day
0  2013      1    1
1  2013      1    1
2  2013      1    1
3  2013      1    1
4  2013      1    1

In [19]:
data_flights.drop(['year','month','day'], axis=1).head()

dep_time  sched_dep_time  dep_delay  arr_time  sched_arr_time  arr_delay  \
0     517.0             515        2.0     830.0             819       11.0   
1     533.0             529        4.0     850.0             830       20.0   
2     542.0             540        2.0     923.0             850       33.0   
3     544.0             545       -1.0    1004.0            1022      -18.0   
4     554.0             600       -6.0     812.0             837      -25.0   

  carrier  flight tailnum origin dest  air_time  distance  hour  minute  \
0      UA    1545  N14228    EWR  IAH     227.0      1400     5      15   
1      UA    1714  N24211    LGA  IAH     227.0      1416     5      29   
2      AA    1141  N619AA    JFK  MIA     160.0      1089     5      40   
3      B6     725  N804JB    JFK  BQN     183.0      1576     5      45   
4      DL     461  N668DN    LGA  ATL     116.0       762     6       0   

             time_hour  
0  2013-01-01 05:00:00  
1  2013-01-01 05:00:00  
2  2013-01-01 05:00:00  
3  2013-01-01 05:00:00  
4  2013-01-01 06:00:00

### Exercise 3

In [2]:
A = pd.read_csv("some_birth_dates1.csv")

In [3]:
B = pd.read_csv("some_birth_dates2.csv")

In [4]:
C = pd.read_csv("some_birth_dates3.csv")

In [5]:
A

Name   BirthDate
0     Paitoon Ornwimol  26.06.1958
1         Antónia Lata  20.05.1935
2    Bertoldo Mallozzi  17.08.1972
3        Nedeljko Bukv  19.12.1921
4        Micha Kitchen  17.09.1930
5      Mefodiy Shachar  01.10.1914
6         Paul Meckler  29.09.1968
7      Katarzyna Lasko  20.10.1971
8         Åge Trelstad  07.03.1935
9  Duchanee Panomyaong  19.06.1952

In [6]:
B

Name   BirthDate
0    Hushang Naigamwala  25.08.1991
1              Zhen Wei  16.11.1975
2         Micha Kitchen  17.09.1930
3           Jodoc Alwin  16.11.1969
4            Igor Mazał  14.05.2004
5       Katarzyna Lasko  20.10.1971
6   Duchanee Panomyaong  19.06.1952
7       Mefodiy Shachar  01.10.1914
8          Paul Meckler  29.09.1968
9         Noe Tae-Woong  11.07.1970
10         Åge Trelstad  07.03.1935

In [7]:
C

Name   BirthDate
0           Jodoc Alwin  16.11.1969
1    Hushang Naigamwala  25.08.1991
2              Zhen Wei  16.11.1975
3         Noe Tae-Woong  11.07.1970
4      Didier Cuvillier  24.04.1938
5     El Bachir al-Aziz  24.01.1999
6      Garikoitz Oguiza  27.05.1970
7        Magyar Flórián  29.12.1962
8      Eufebio Mascioli  11.06.1921
9            Aline Rush  04.09.1916
10        Lamija Osmond  11.04.1926
11       Étienne Chaney  04.09.1983
12       Ewelina Musial  01.12.1962
13             Yang Xun  13.04.1992
14  Gavrilo Dzenopoljac  21.07.1927
15             Tang Xia  28.04.1989
16         Mifune Nampo  18.10.1926
17       Mamuka Tercero  14.09.1912
18       Juba Kunimatsu  31.07.1929

#### Union of A and B

In [8]:
pd.concat([A,B]).drop_duplicates(keep='first')

Name   BirthDate
0     Paitoon Ornwimol  26.06.1958
1         Antónia Lata  20.05.1935
2    Bertoldo Mallozzi  17.08.1972
3        Nedeljko Bukv  19.12.1921
4        Micha Kitchen  17.09.1930
5      Mefodiy Shachar  01.10.1914
6         Paul Meckler  29.09.1968
7      Katarzyna Lasko  20.10.1971
8         Åge Trelstad  07.03.1935
9  Duchanee Panomyaong  19.06.1952
0   Hushang Naigamwala  25.08.1991
1             Zhen Wei  16.11.1975
3          Jodoc Alwin  16.11.1969
4           Igor Mazał  14.05.2004
9        Noe Tae-Woong  11.07.1970

#### Union of A and B and C

In [9]:
pd.concat([A,B,C]).drop_duplicates(keep="first")

Name   BirthDate
0      Paitoon Ornwimol  26.06.1958
1          Antónia Lata  20.05.1935
2     Bertoldo Mallozzi  17.08.1972
3         Nedeljko Bukv  19.12.1921
4         Micha Kitchen  17.09.1930
5       Mefodiy Shachar  01.10.1914
6          Paul Meckler  29.09.1968
7       Katarzyna Lasko  20.10.1971
8          Åge Trelstad  07.03.1935
9   Duchanee Panomyaong  19.06.1952
0    Hushang Naigamwala  25.08.1991
1              Zhen Wei  16.11.1975
3           Jodoc Alwin  16.11.1969
4            Igor Mazał  14.05.2004
9         Noe Tae-Woong  11.07.1970
4      Didier Cuvillier  24.04.1938
5     El Bachir al-Aziz  24.01.1999
6      Garikoitz Oguiza  27.05.1970
7        Magyar Flórián  29.12.1962
8      Eufebio Mascioli  11.06.1921
9            Aline Rush  04.09.1916
10        Lamija Osmond  11.04.1926
11       Étienne Chaney  04.09.1983
12       Ewelina Musial  01.12.1962
13             Yang Xun  13.04.1992
14  Gavrilo Dzenopoljac  21.07.1927
15             Tang Xia  28.04.1989
16         Mifune Nampo  18.10.1926
17       Mamuka Tercero  14.09.1912
18       Juba Kunimatsu  31.07.1929

#### Intersection of A and B

In [10]:
A[A.Name.isin(B.Name)]

Name   BirthDate
4        Micha Kitchen  17.09.1930
5      Mefodiy Shachar  01.10.1914
6         Paul Meckler  29.09.1968
7      Katarzyna Lasko  20.10.1971
8         Åge Trelstad  07.03.1935
9  Duchanee Panomyaong  19.06.1952

#### Intersection of A and C

In [11]:
A[A.Name.isin(C.Name)]

Empty DataFrame
Columns: [Name, BirthDate]
Index: []

#### Difference of A and B

In [30]:
A[A.Name.isin(B.Name) == False]

Name   BirthDate
0   Paitoon Ornwimol  26.06.1958
1       Antónia Lata  20.05.1935
2  Bertoldo Mallozzi  17.08.1972
3      Nedeljko Bukv  19.12.1921